language: python
python:
- '3.6'
install:
- pip install -r requirements.txt --no-build-isolation
- pip install -r dev-requirements.txt --no-build-isolation
- pip install codecov
- cp ci/settings.py accessCeramics/local_settings.py
- python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> accessCeramics/local_settings.py
script:
- pytest --cov=accessCeramics
services:
- mysql
after_success:
- codecov