language: python
python:
- '3.6'
cache: pip
install:
- pip install -r requirements.txt
- pip install -r dev-requirements.txt
- pip install codecov
- cp ci/settings.py accessCeramics/local_settings.py
- python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> accessCeramics/local_settings.py
script:
- pytest --cov=accessCeramics # run the tests
- sphinx-build -nWT -b dummy docs-src docs/html # lint the documentation
services:
- mysql
after_success:
- codecov