# Generated by Django 2.0.4 on 2018-04-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when work was last edited.'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(help_text='A short description of the work.', null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(help_text='The title of the work. Max 500 characters.', max_length=500),
        ),
    ]
