# Generated by Django 2.0.5 on 2018-06-02 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pyrometriccone',
            old_name='value',
            new_name='number',
        ),
    ]
