# Generated by Django 2.0.4 on 2018-04-13 20:36

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20180413_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when work was deposited in accessCeramics.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='date',
            field=models.DateField(default=datetime.date(2018, 4, 13), help_text='Date of the work.'),
            preserve_default=False,
        ),
    ]
