# Generated by Django 2.0.5 on 2018-06-02 17:55

from django.db import migrations

CONE_NUMBERS = [
    '022',
    '021',
    '020',
    '019',
    '018',
    '017',
    '016',
    '015',
    '014',
    '013',
    '012',
    '011',
    '010',
    '09',
    '08',
    '07',
    '06',
    '05',
    '04',
    '03½',
    '03',
    '02',
    '01',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
    '11',
    '12',
    '13'
]

def add_cones(apps, schema_editor):
    # Add a set of known cones to the database.
    PyrometricCone = apps.get_model('works', 'PyrometricCone')
    for number in CONE_NUMBERS:
        PyrometricCone(number=number).save()

class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_cone_number'),
    ]

    operations = [
        migrations.RunPython(add_cones)
    ]
