# Generated by Django 2.0.4 on 2018-04-13 21:12

from django.db import migrations, models
import django_measurement.models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20180413_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='depth',
            field=django_measurement.models.MeasurementField(help_text='Depth of the work.', measurement_class='Distance', null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='height',
            field=django_measurement.models.MeasurementField(help_text='Height of the work.', measurement_class='Distance', null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='width',
            field=django_measurement.models.MeasurementField(help_text='Width of the work.', measurement_class='Distance', null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, help_text='A short description of the work.', null=True),
        ),
    ]
