# Generated by Django 2.0.7 on 2018-07-06 19:16

from django.db import migrations
import django_measurement.models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_cone_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='second_firing_temperature',
            field=django_measurement.models.MeasurementField(blank=True, measurement_class='Temperature', null=True),
        ),
    ]
