# Generated by Django 2.0.7 on 2018-08-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_work_second_firing_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.PositiveSmallIntegerField(help_text='YYYY format.'),
        ),
    ]
