# Generated by Django 2.0.4 on 2018-04-22 02:32

from django.conf import settings
from django.db import migrations, models
import django_measurement.models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20180413_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django_measurement.models.MeasurementField(measurement_class='Temperature')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='credits',
            field=models.TextField(blank=True, help_text='Credit line, e.g. for photographing the work.', null=True),
        ),
        migrations.AlterField(
            model_name='technique',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='work',
            name='creators',
            field=models.ManyToManyField(help_text='Must be an extant accessCeramics user.', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='depth',
            field=django_measurement.models.MeasurementField(measurement_class='Distance', null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(blank=True, help_text="A description of the work or artist's statement.", null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='height',
            field=django_measurement.models.MeasurementField(measurement_class='Distance', null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='materials',
            field=models.ManyToManyField(to='works.Material'),
        ),
        migrations.AlterField(
            model_name='work',
            name='techniques',
            field=models.ManyToManyField(to='works.Technique'),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(help_text='500 characters maximum.', max_length=500),
        ),
        migrations.AlterField(
            model_name='work',
            name='width',
            field=django_measurement.models.MeasurementField(measurement_class='Distance', null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_types',
            field=models.ManyToManyField(to='works.WorkType'),
        ),
        migrations.AddField(
            model_name='work',
            name='temperatures',
            field=models.ManyToManyField(to='works.Temperature'),
        ),
    ]
