# Generated by Django 2.0.4 on 2018-04-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_auto_20180422_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.PositiveSmallIntegerField(help_text='Date in YYYY format.'),
        ),
    ]
