# Generated by Django 2.0.5 on 2018-05-28 20:06

from django.db import migrations, models
import django_measurement.models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_auto_20180422_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='credits',
            new_name='credit',
        ),
        migrations.AlterField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.PositiveSmallIntegerField(help_text='Use YYYY format.'),
        ),
        migrations.AlterField(
            model_name='work',
            name='depth',
            field=django_measurement.models.MeasurementField(blank=True, measurement_class='Distance', null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='height',
            field=django_measurement.models.MeasurementField(blank=True, measurement_class='Distance', null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='materials',
            field=models.ManyToManyField(blank=True, to='works.Material'),
        ),
        migrations.AlterField(
            model_name='work',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='techniques',
            field=models.ManyToManyField(blank=True, to='works.Technique'),
        ),
        migrations.AlterField(
            model_name='work',
            name='temperatures',
            field=models.ManyToManyField(blank=True, to='works.Temperature'),
        ),
        migrations.AlterField(
            model_name='work',
            name='width',
            field=django_measurement.models.MeasurementField(blank=True, measurement_class='Distance', null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_types',
            field=models.ManyToManyField(blank=True, to='works.WorkType'),
        ),
    ]
